### ISSUE TITLE
Adding api to search for stocks given a keyword

### ISSUE THREAD

**Issue by nikhilesh20** [alpacahq/alpaca-trade-api-go#102]
I see that there is an endpoint to search for stocks - https://app.alpaca.markets/internal/assets/search?query=aap Is there any equivalent go api, if not can we add one?

**Comment by shlomikushchi** [comment]
Hi, this is not a documented api, so it is not supported.
to see supported apis go here: https://alpaca.markets/docs/api-documentation/api-v2/assets/
