### ISSUE TITLE
Add ReplacedBy to Orders struct

### ISSUE THREAD

**Issue by ejbrever** [alpacahq/alpaca-trade-api-go#105]
Hi, ReplacedBy is not in the Orders struct:
https://godoc.org/github.com/alpacahq/alpaca-trade-api-go/alpaca#Order

Would it be possible to get this added? I see it is available in the REST API:
![Screenshot](https://user-images.githubusercontent.com/19435055/102965700-3ab17b00-44a3-11eb-8a8b-369ed30cd1ca.png)

**Comment by ejbrever** [comment]
Looks like this is just a really quick one line addition. I was able to test locally, but I don't have permission to create a PR. Is it possible for me to get access to send over a PR for review or is someone able to add this line:

ReplacedBy     *string          `json:"replaced_by"`

After this line:
https://github.com/alpacahq/alpaca-trade-api-go/blob/master/alpaca/entities.go#L50

Thanks.

**Comment by shlomikushchi** [comment]
hi, 
anyone could create a PR
you need to fork and then it will be possible
lmk if you want to do that or I will just add the line myself

**Comment by ejbrever** [comment]
Ah, thanks! Just sent over PR #106
