### ISSUE TITLE
Add missing params to ListOrders

### ISSUE THREAD

**Issue by coopernurse** [alpacahq/alpaca-trade-api-go#108]
ListOrders currently supports a subset of the available params.  Missing params:

* after
* direction
* symbols

I'd suggest we add a new method that accepts a request struct that includes all supported params.  I'm open to naming suggestions.  We could deprecate the old method.  The result would be something like:

```
func (c *Client) ListOrders(status *string, until *time.Time, limit *int, nested *bool) ([]Order, error) {
	req := ListOrdersRequest{
		Status: status,
		Until:  until,
		Limit:  limit,
		Nested: nested,
	}
	return c.ListOrders2(req)
}

func (c *Client) ListOrders2(req ListOrdersRequest) ([]Order, error) {
// code here
}
```

**Comment by gnvk** [comment]
Closed by https://github.com/alpacahq/alpaca-trade-api-go/commit/91b047240e0c1a4fd9726c699d0fdd405435decf
