### ISSUE TITLE
PlaceOrderRequest missing extended-hours field

### ISSUE THREAD

**Issue by ajyuan** [alpacahq/alpaca-trade-api-go#111]
The `PlaceOrderRequest` struct seems to be missing the `extended_hours` field described in [Alpaca's API documentation](https://alpaca.markets/docs/api-documentation/api-v2/orders/). Could we see this field added?

**Comment by rafaeelaudibert** [comment]
I see the field there, apparently added by #72. Could you confirm and, maybe, close this issue if that's the case?

**Comment by ajyuan** [comment]
I’m not longer using this API, so I’ll go ahead and close the issue. Thanks.
