### ISSUE TITLE
Reconnect fail on nil interface

### ISSUE THREAD

**Issue by imthaghost** [alpacahq/alpaca-trade-api-go#114]
Lines 188-203 when given an unexpected EOF exception continues on to the reconnect function. The reconnect function assumes that the interface will not be nil (the value becomes nil by some other part of the code) throws a unneeded panic which kills the entire program.

https://github.com/alpacahq/alpaca-trade-api-go/blob/master/alpaca/stream.go#L200
```golang
else {
			if websocket.IsCloseError(err) {
				// if this was a graceful closure, don't reconnect
				if s.closed.Load().(bool) {
					return
				}
			} else {
				log.Printf("alpaca stream read error (%v)", err)
			}

			err := s.reconnect()
			if err != nil {
				panic(err)
			}
		}
	}
```

Stack Trace:
![Screen Shot 2021-02-08 at 2 23 42 PM](https://user-images.githubusercontent.com/46610773/107289542-10e3f180-6a1a-11eb-997d-e4e2396f9204.png)

Resolution:

It would be nice to either nil check the interface before converting to a string. Or returned an error message instead of a panic so the program isn't killed.

**Comment by gnvk** [comment]
Fixed by v2.
