### ISSUE TITLE
Authentication regression

### ISSUE THREAD

**Issue by istrau2** [alpacahq/alpaca-trade-api-go#129]
We are seeing these error messages:
> request is unauthorized (generate APCA-API-KEY-ID and APCA-API-ACCESS-SECRET-KEY from dashboard and include in HTTP header) (Code = 40110000)

which makes sense given this line: https://github.com/alpacahq/alpaca-trade-api-go/blob/v1/alpaca/rest.go#L41

**Comment by gnvk** [comment]
Please try v2. If you still see the issue, reopen the ticket. Thanks!
