### ISSUE TITLE
alpaca.auth() (stream.go) depends on common.Credentials()

### ISSUE THREAD

**Issue by andresvia** [alpacahq/alpaca-trade-api-go#138]
One should not expose secrets in environment variables as they are easily hackable in shared environments, I would like to instead, load credentials from a custom secure location at runtime even for streaming, but the fact that `stream.go` hardcodes the credentials source from common.Credentials() makes this an impossible task.

https://github.com/alpacahq/alpaca-trade-api-go/blob/28427ca5425285bf1ec5eb431451eae6ed770ed0/alpaca/stream.go#L258-L264

A pattern for `stream.Register(...)` like `alpaca.NewClient(...)` should be supported.

```
	client := alpaca.NewClient(&common.APIKey{
		ID: "XXX",
		PolygonKeyID: "XXX",
		Secret: "YYY",
	})
```

I'll be happy to try to implement it.

Update: It seems like @istrau2 made progress some time ago, this could be used as a starting point https://github.com/alpacahq/alpaca-trade-api-go/pull/79

**Comment by gnvk** [comment]
This should be fixed by v2. Please check it out!
