### ISSUE TITLE
Add a newer version tag to the repository

### ISSUE THREAD

**Issue by pyohannes** [alpacahq/alpaca-trade-api-go#18]
When using `go mod`, it by defaults downloads `v1.0.0` of `alpaca-trade-api-go`, which is very old (from December) and which is out-of-sync with the API documentation.

Manually changing the version from `v1.0.0` to `master` helps.

Here's a sample session:
```
$ cat <<EOF > main.go
package main

import (
        "github.com/alpacahq/alpaca-trade-api-go/alpaca"
)

func main() {
        alpaca.SetBaseUrl("https://api.alpaca.markets")
}
EOF
$ go mod init
go: creating new go.mod: module github.com/pyohannes/gotrade/example
$ go mod download
$ go build
go: finding github.com/alpacahq/alpaca-trade-api-go/alpaca latest
# github.com/pyohannes/gotrade/example
./main.go:8:2: undefined: alpaca.SetBaseUrl
$ sed -i s/v1.0.0/master/ go.mod
$ go build
go: finding github.com/alpacahq/alpaca-trade-api-go master
$
```
Please add a new version tag which is in sync with the published API documentation.

**Comment by umitanuki** [comment]
Makes sense. Will do that.

**Comment by umitanuki** [comment]
Sorry for late. Just pushed v1.1.0 for latest master
