### ISSUE TITLE
Take Profit Price on Market Order Not Working

### ISSUE THREAD

**Issue by jayp0521** [alpacahq/alpaca-trade-api-go#181]
Hello,

I am making a place order request in the follow format. Assume all inputs are correctly formatted. In addition, assume the *takeProfitPrice* is greater than the current market value for the *AssetKey*. Knowing the above. I make an order and submit. However the order gets processed successfully, but the LimitPrice for TP is not propagating for some reason. It just is not there. Is there a reason for this? I read the docs and I don't see that I am doing anything wrong. I can place the same exact in that format on alpaca website, so unsure what the issue is.

```go
placeOrderRequest = alpaca.PlaceOrderRequest{
	AssetKey: &ticker,
	Qty:      &qty,
	TakeProfit: &alpaca.TakeProfit{
		LimitPrice: &takeProfitPrice,
	},
	Type:        alpaca.Market,
	TimeInForce: alpaca.Day,
	Side:        side,
}
```

**Comment by jayp0521** [comment]
Any update?

**Comment by gnvk** [comment]
You are not providing an order class for your order, which means that the default "market" will be used, thus the `TakeProfit` field is simply ignored. Add this line to your `PlaceOrderRequest`
``` go
OrderClass:  alpaca.Oto
```
to create an OTO (One Triggers the Other) order with a take profit leg with your `takeProfitPrice`.
