### ISSUE TITLE
Add example for Authentication.

### ISSUE THREAD

**Issue by WikipediaBrown** [alpacahq/alpaca-trade-api-go#195]
The issue here is that I am looking to use the Go library for my implementation but I need a little more info on how to get get streaming the KYC flow working with the go library. Let me know if there's anything I can do to help.

**Comment by JohnAllen** [comment]
9 months later and the example still doesn't work and I am the third person to request it. Would be so amazing if examples required everything to work except credentials.

**Comment by gnvk** [comment]
@JohnAllen @WikipediaBrown What is exactly that you'd need an example for?

**Comment by dnapier** [comment]
I believe they're asking for an example pointing out that credentials are set via environmental variables. You wouldn't know this without looking into how the library runs.

```go
os.Setenv("APCA_API_KEY_ID", "<KEY>")
os.Setenv("APCA_API_SECRET_ID", "<KEY>")
```

These should do the trick for anyone looking.

**Comment by gnvk** [comment]
Do you mean this: https://github.com/alpacahq/alpaca-trade-api-go#authentication

**Comment by dnapier** [comment]
LGTM! No idea what they're asking for then..
