### ISSUE TITLE
Connect stock and news streams simultaneously

### ISSUE THREAD

**Issue by petric3** [alpacahq/alpaca-trade-api-go#201]
Hello, have posted this in alpaca forum, but no reply. Perhaps is also interested for devs here. I’d like to stream stock data and stock news simultaneously, my code:
```
cStock := stream.NewStocksClient(
“sip”,
stream.WithTrades(tradeHandler, symbols…),
stream.WithQuotes(quoteHandler, symbols…),
stream.WithCredentials(xy,xy),
stream.WithReconnectSettings(20, 1*time.Second),
stream.WithProcessors(1),
)

cNws := stream.NewNewsClient(
stream.WithCredentials(xy,xy),
stream.WithNews(newsHandler, symbols…),
stream.WithReconnectSettings(20, 1*time.Second),
stream.WithProcessors(1),
)

ctx, cancel := context.WithCancel(context.Background())
defer cancel()

if err := cStock.Connect(ctx); err != nil {
log.Fatalf(“could not establish connection, error: %s”, err)
}
if err := cNws.Connect(ctx); err != nil {
log.Fatalf(“could not establish connection, error: %s”, err)
}
```

but am getting the following error on the news connection, i.e. 2nd connection like there cannot be two simultaneous authentications:
```
2022/05/23 11:21:04 INFO datav2stream: connecting to wss://stream.data.alpaca.markets/v2/sip, attempt 1/20 …

2022/05/23 11:21:05 INFO datav2stream: established connection

2022/05/23 11:21:05 INFO datav2stream: finished connection setup

established connection stocks

2022/05/23 11:21:06 INFO datav2stream: connecting to wss://stream.data.alpaca.markets/v1beta1/news, attempt 1/20 …

2022/05/23 11:21:06 INFO datav2stream: established connection

2022/05/23 11:21:06 INFO datav2stream: auth error: connection limit exceeded 2022/05/23 11:21:06 INFO datav2stream: retrying auth in 500ms, attempt 2/16
```
Is there a way to stream stocks and news data simultaneously within the single code? It works fine for two separate codes run simultaneously.

**Comment by gnvk** [comment]
This is strange. Your code without any modifications works for me. The stock stream should not cause "connection limit exceeded" error on the news stream, and vice versa. Are you sure you're not having another news stream open while running your program? That's the only thing I can guess.

**Comment by petric3** [comment]
yes, it was opened on my little server, have tested it now and it works nicely. Sorry for that and thank you for your reply 🙏🏼 🙇🏼‍♂️
