### ISSUE TITLE
panic: nats: Authorization Violation

### ISSUE THREAD

**Issue by bonly** [alpacahq/alpaca-trade-api-go#21]
panic: nats: Authorization Violation

note: 
1. common not import
2. json not import 
3. key and id had modify to mine

src:
import (
    "os"
    "fmt"

    "github.com/alpacahq/alpaca-trade-api-go/alpaca"
    "github.com/alpacahq/alpaca-trade-api-go/polygon"
    "github.com/alpacahq/alpaca-trade-api-go/stream"
    nats "github.com/nats-io/go-nats"
)

func main() {
    os.Setenv(common.EnvApiKeyID, "<key_id>")
    os.Setenv(common.EnvApiSecretKey, "<secret_key>")

    if err := stream.Register(alpaca.TradeUpdates, tradeHandler); err != nil {
        panic(err)
    }

    if err := stream.Register("Q.AAPL", quoteHandler); err != nil {
        panic(err)
    }

    select{}
}

func tradeHandler(msg interface{}) {
    fmt.Println(msg)
}

func quoteHandler(msg interface{}) {
    quote := polygon.StreamQuote{}

    if err := json.Unmarshal(msg.(*nats.Msg).Data, &quote); err != nil {
        panic(err)
    }

    fmt.Println(quote.Symbol, quote.BidPrice, quote.BidSize, quote.AskPrice, quote.AskSize)
}

**Comment by bdowling** [comment]
This issue is likely related.  Polygon data api is only accessible to funded accounts.  We will update the examples to clarify this. 

https://alpaca-community.slack.com/archives/CD9H46RGX/p1555637686139300?thread_ts=1555637686.139300&cid=CD9H46RGX

**Comment by ttt733** [comment]
Updated the Readme with a line explaining this.
