### ISSUE TITLE
ListOrdersRequest lacks query parameter `side`

### ISSUE THREAD

**Issue by gfelbing** [alpacahq/alpaca-trade-api-go#220]
As the title says, the ListOrdersRequest entity lacks the parameter `side`:

https://github.com/alpacahq/alpaca-trade-api-go/blob/master/alpaca/entities.go#L237

See [API Docs](https://alpaca.markets/docs/api-references/trading-api/orders/#get-a-list-of-orders).

**Comment by gnvk** [comment]
This will be fixed shortly in v3.
