### ISSUE TITLE
Broker API authentication is not supported

### ISSUE THREAD

**Issue by st-wong** [alpacahq/alpaca-trade-api-go#243]
Getting `403` error when providing `APIKey` and `APISecret` via `ClientOpts`. Noticed that they're being set via Headers but they should be set via `req.SetBasicAuth(APIKey, APISecret)`?

**Comment by victorouse** [comment]
Just bumping with reference to the Python SDK adding support for basic authorisation.

- https://github.com/alpacahq/alpaca-py/pull/250

Also mentioned here:

- https://github.com/alpacahq/alpaca-trade-api-csharp/issues/599

**Comment by gnvk** [comment]
Basic auth is only used for the Broker API, which is not currently supported by this SDK. Would you be interested in it? Probably only for market data?

**Comment by gnvk** [comment]
No, the Broker API is not supported by this library at the moment. And based on the number of replies to my previous comment it doesn't look like it's much requested either :P

**Comment by JayBusch** [comment]
Ok, well if there are no plans to support it, perhaps the functions that require it should be removed?  Its a bit misleading to have dead code present.

**Comment by gnvk** [comment]
Which functions require it?

**Comment by JayBusch** [comment]
It would seem that GetCalendar does, unless I'm (hopefully) mistaken?  On my mobile currently so basing that off the 403 I got earlier and the content of this issue; not able to dive in and verify via the code until I get back to my machine tommorow.

**Comment by gnvk** [comment]
`GetCalendar` and all the other functions work with "normal", non-broker authentication.

**Comment by gnvk** [comment]
@JayBusch Could you please check if it works now? :)

**Comment by JayBusch** [comment]
Yes I will this afternoon.  Thank you for looking into it.

**Comment by JayBusch** [comment]
Ok, so I've synced my fork and merged the changes so I can test with my application.  All seems well, except I think I have a misunderstanding regarding the BrokerAPI Keys.  I may not have access to this API.  I only have the lowly retail subscription @ 9$/mo.  My intention was to get access to the available trading days for a date range and  I am confused as to whether this requires the Broker API or if it the Market Data API has the endpoint available - and if I would even be able to access the Broker API without upgrading my account in some way.

It seems that the Market Data API has the Calendar endpoint defined for at least v2 (https://docs.alpaca.markets/reference/getcalendar-1).  I'm not sure if this was moved to the Broker API for v3?

Sorry for my confusion, I only had a short time to look into this today, if you could clarify any of this for me I would much appreciate it.  Currently, if I use my MarketData API Keys in both the APIKey/APISecret and BrokerKey/BrokerSecret fields of alpaca.ClientOpts I get a 403 when calling the GetCalendar function.  I am able to authenticate and pull other MarketData API data.

**Comment by gnvk** [comment]
@JayBusch What's the first character of your API key? Based one what you wrote my best guess is that you're using a paper API Key (stating with a `P`), for which you need to set the base URL to <https://paper-api.alpaca.markets> as [in this example](https://github.com/alpacahq/alpaca-trade-api-go/?tab=readme-ov-file#trading-rest-example).

**Comment by JayBusch** [comment]
My API KEY does not start with a P.

I tried generating new keys, and as a result I can no longer auth with any API using the library.  My new keys work well in the API docs examples and with curl.  I will debug further this afternoon after some family responsibilities to see if I can determine why.

**Comment by JayBusch** [comment]
So it seems after re-generating my keys it is just the Trading API I cannot access.  The Market Data API seems to be fine.  The Trading API was working fine with my previous key/secret pair.

**Comment by JayBusch** [comment]
If I use a marketdata client with both the APIKey/APISecret and BrokerKey/BrokerKey client defined in the options I get a 403 on any call.  If I only define the APIKey/APISecret I can make requests for Trades and Bars but not GetCalendar.

I presume now that this is by design and that I simply need to have another marketdata client for BrokerAPI related calls.  I will try to test this next but it may take me a moment as it's been a busy weekend outside of this matter.

**Comment by gnvk** [comment]
@JayBusch If you have time, could you please dm me on [Slack](https://alpaca-community.slack.com/ssb/redirect) so that I can help you debug this issue?

**Comment by JayBusch** [comment]
Sorry, busy week.

How can I get access to the workspace?
