### ISSUE TITLE
issue with timestamp returning wrong timezone

### ISSUE THREAD

**Issue by taewdy** [alpacahq/alpaca-trade-api-go#247]
When I get historical market data with 1 day timeframe , it returns 5:00am UTC for closing time.

Shouldn't this be in EST timezone? I can just adjust this by adding number of hours instead, but shouldn't this be fixed

or am I missing something somewhere?

see the timestamp returns 5:00am UTC as its closing time.

![Screenshot 2023-05-16 at 2 50 29 pm](https://github.com/alpacahq/alpaca-trade-api-go/assets/19986368/86ef6412-b54f-4049-a9fc-43aa12ef34b1)
![Screenshot 2023-05-16 at 2 43 00 pm](https://github.com/alpacahq/alpaca-trade-api-go/assets/19986368/eec089ba-7bec-4a8f-a515-ad79a383c5d8)

**Comment by taewootafe** [comment]
It's just 12am is used for close time, if that's the case, please close the issue. just wanted to clarify

**Comment by taewdy** [comment]
It's just 12am is used for close time, if that's the case, please close the issue. just wanted to clarify
