### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by PopeDCM** [alpacahq/alpaca-trade-api-go#251]
After running
`go install github.com/alpacahq/alpaca-trade-api-go/v3/alpaca@latest`
I get the error
`The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.`

**Comment by gnvk** [comment]
Now the error message is clearer:
``` 
$ go install github.com/alpacahq/alpaca-trade-api-go/v3/alpaca@latest
package github.com/alpacahq/alpaca-trade-api-go/v3/alpaca is not a main package
```

You can't "install" the SDK, because it's a library, not an executable. As @lilcriispy and the [readme](https://github.com/alpacahq/alpaca-trade-api-go#installation) suggests, use `go get` or `go mod tidy` to add it to your project.
