### ISSUE TITLE
Go package installation doesn't work

### ISSUE THREAD

**Issue by BattulgaTS** [alpacahq/alpaca-trade-api-go#26]
Hello, I've tried installing package from the terminal with this command
`go get github.com/alpacahq/alpaca-trade-api-go`.

Unfortunately, I'm getting an error saying
`can't load package: package github.com/alpacahq/alpaca-trade-api-go: no Go files in /Users/tulga/go/src/github.com/alpacahq/alpaca-trade-api-go`.

**Comment by BattulgaTS** [comment]
It appears that I can install sub packages individually by running
`go get github.com/alpacahq/alpaca-trade-api-go/polygon`
`go get github.com/alpacahq/alpaca-trade-api-go/stream`.

I don't see the main package here but all sub packages.
https://godoc.org/?q=alpaca

**Comment by umitanuki** [comment]
Right, there is nothing to import at the top directory.

**Comment by umitanuki** [comment]
So technically the top directory is not a go package.

**Comment by tclzcja** [comment]
Sorry for replying on a closed ticket, but there's some inconsistency between the solution @theTulga provided (which works) and the tutorial at https://github.com/alpacahq/alpaca-trade-api-go. Should we install the packages individually? Or there will be a dummy go file created in the top directory?
