### ISSUE TITLE
'Close position and Sleep until market close' doesn't run

### ISSUE THREAD

**Issue by nickforce** [alpacahq/alpaca-trade-api-go#264]
Hi, I'm testing with the mean-reversion example - the logic to close position and sleep until market close (lines 129-140) doesn't seem to be triggered. Having trouble debugging this- I'm using the exact mean-reversion example code also. Thanks for taking a look!

```
		clock, err := algo.tradeClient.GetClock()
		if err != nil {
			log.Fatalf("Failed to get clock: %v", err)
		}
		untilClose := clock.NextClose.Sub(clock.Timestamp.Add(-15 * time.Minute))
		time.Sleep(untilClose)

		fmt.Println("Market closing soon. Closing position.")
		if _, err := algo.tradeClient.ClosePosition(algo.stock, alpaca.ClosePositionRequest{}); err != nil {
			log.Fatalf("Failed to close position: %v", algo.stock)
		}
		fmt.Println("Position closed.")
```

**Comment by gnvk** [comment]
What do you mean exactly by "doesn't seem to be triggered"? I'd recommend adding a log line before the sleep, e.g.
``` go
fmt.Printf("Market closing at %s. Waiting for %s...\n", clock.NextClose, untilClose)
```
Then you'll see exactly how much the algo sleeps before market close.

**Comment by nickforce** [comment]
@gnvk I mean it just keeps placing orders into the market close. I would expect the code to close all positions and sleep at 15minutes before market close

**Comment by nickforce** [comment]
The log line helped clear up the order the sleep was happening. Thank you! @gnvk

**Comment by nickforce** [comment]
@gnvk Yes, from what I have seen it is intermittent. But I do see orders happening even after the 15 minutes prior to market close logic runs.
