### ISSUE TITLE
Add position fill time

### ISSUE THREAD

**Issue by petric3** [alpacahq/alpaca-trade-api-go#270]
I trade intraday and also do swing trading. There can naturally be couple of positions of the same symbol. 

I'm writing a script to liquidate a position. For that I'd need a position's fill/created timestamp and interestingly such a basic/important information is not provided [here](https://github.com/alpacahq/alpaca-trade-api-go/blob/cfec3c6c98d91d6ba2c8fb3a6302a7a94a7beec2/alpaca/entities.go#L94). Could you please add it? Or perhaps, there's a workaround? Thank you!

**Comment by gnvk** [comment]
Here's why I don't think positions should have fill / created timestamp:
- A position can be made of multiple orders (e.g. you buy 1 + 1 AAPL). In that case what's the created timestamp? The first? The last?
- The position ceases to exist when the underlying order is filled. So by the time you would want to see the filled timestamp, it won't be there. 

The fill / created timestamp is the property of orders. When you create an order, it will have a created timestamp, and when it gets filled, its filled timestamp will be updated. You have two options to get these:
1. Pull: [GetOrder](https://github.com/alpacahq/alpaca-trade-api-go/blob/cfec3c6c98d91d6ba2c8fb3a6302a7a94a7beec2/alpaca/rest.go#L534)
2. Stream: [StreamTradeUpdates](https://github.com/alpacahq/alpaca-trade-api-go/blob/cfec3c6c98d91d6ba2c8fb3a6302a7a94a7beec2/alpaca/stream.go#L26)

If you're happy with these options, please close this issue.
