### ISSUE TITLE
PlaceOrderRequest is missing `position_intent` query param

### ISSUE THREAD

**Issue by gcatlin** [alpacahq/alpaca-trade-api-go#289]
It would be good to have constants for the intents; e.g. `BuyToOpen`, `SellToClose`, etc.

https://docs.alpaca.markets/reference/postorder

**Comment by ankitsridhar16** [comment]
Is `CreateOrder` implemented already?

**Comment by gcatlin** [comment]
Apologies, I meant `PlaceOrder`. I'll update the description.

**Comment by ankitsridhar16** [comment]
I can work on this @gcatlin

**Comment by gcatlin** [comment]
Great, thanks! 👍

**Comment by ankitsridhar16** [comment]
@gcatlin I have created a PR- https://github.com/alpacahq/alpaca-trade-api-go/pull/294 can you take a look and suggest me changes if required

**Comment by mips171** [comment]
Is this in the current release? I am using the examples provided in https://github.com/alpacahq/alpaca-trade-api-go/blob/master/examples/long-short/long-short.go but get the same issue.

`Order of | 207 INTC buy | did not go through: invalid position_intent specified (HTTP 422, Code 40010001)`

I also get this, so maybe the example is out of date?
`Failed to rebalance, will try again in a minute: get total long price: get snapshots: Invalid format for parameter symbols: query parameter 'symbols' is required (HTTP 400)`
