### ISSUE TITLE
Base URL needs to be configurable

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/alpaca-trade-api-go#4]
For paper trading and other testing purposes, API base URL should be configurable.

**Comment by nu11ptr** [comment]
Just came here to file this as well, but I see it already is. Base URL should not be an environment variable only, but should be configurable. This isn't just for flexibility, but also to allow multiple instances of the client to be accessing a paper and prod account at the same time.

**Comment by bobvdvalk** [comment]
Something done with this?

**Comment by ttt733** [comment]
Addressed this with PR #14 - sorry for the wait!
