### ISSUE TITLE
Add the ability to update the Data Url

### ISSUE THREAD

**Issue by Insulince** [alpacahq/alpaca-trade-api-go#62]
Similar to how the`base` url can be updated using `SetBaseUrl`, it would be nice to be able to update the data url as well.

My use case for this is I would like to proxy my requests through nginx first to do some additional configurations on the request before sending the response back to the client, but I can only do the for the base url currently.

**Comment by 117** [comment]
In addition to this i'd like to see the base url be client-unique. So you can have a paper and live trading client running at the same time.

**Comment by istrau2** [comment]
+1 why is the baseUrl not client unique?

**Comment by shlomikushchi** [comment]
Hi, when added the alpaca-proxy-agent I added `DATA_PROXY_WS`. this is an environment variable that could be used to replace the data url. I used it for routing through the proxy-agent but it could be used to a custom server too.

**Comment by gnvk** [comment]
This is fixed in v2.
