### ISSUE TITLE
go get results in error

### ISSUE THREAD

**Issue by uhari03** [alpacahq/alpaca-trade-api-go#64]
```
go get github.com/alpacahq/alpaca-trade-api-go
package github.com/alpacahq/alpaca-trade-api-go: no Go files in /c/Code/go/src/github.com/alpacahq/alpaca-trade-api-go
```

Is this expected? Technically the error seems correct are no go files in the root directory.

I'm specifically using Windows Subsystem for Linux, but haven't really had issues with go.

**Comment by uhari03** [comment]
The solution might simple have folks `git clone` the repo instead of running `go get`

`go get` still downloads the repo for you, but it's a weird user experience for them to get that error

**Comment by ttt733** [comment]
This sounds like an issue with your go set up rather than the repo. I'm going to close this, but I'll investigate if more people see issues.
