### ISSUE TITLE
Type mismatch while subscribing to "T.SYMBOL"

### ISSUE THREAD

**Issue by zhurunz** [alpacahq/alpaca-trade-api-go#66]
Error message from the lib:

polygon stream read error (json: cannot unmarshal string into Go struct field StreamTrade.i of type int64)

**Comment by umitanuki** [comment]
Sounds like we need to change https://github.com/alpacahq/alpaca-trade-api-go/blob/8e0717f964276571ee3e00392690ec89ec84429e/polygon/entities.go#L231 to string type

**Comment by zipkr13** [comment]
@zhurunz I have patched this on my machine using the above PR, and have verified it works when streaming from polygon.

**Comment by zipkr13** [comment]
Can this issue be closed now? @umitanuki

**Comment by zhurunz** [comment]
Verify fixed.
