### ISSUE TITLE
Time frames not working

### ISSUE THREAD

**Issue by Fish1** [alpacahq/alpaca-trade-api-go#73]
```
start := time.Now().Add(time.Minute * time.Duration(30))
end := time.Now()
bars, err := client.GetSymbolBars("GOOG", alpaca.ListBarParams {
 TimeFrame: "minute",
 StartDt: &start,
 EndDt: &end,
})
fmt.Println(len(bars))
```
I would expect this to return 30 bars, but instead, it returns the default 100 bars no matter what times I set.

**Comment by drew-wallace** [comment]
Shouldn't start be in the past?

**Comment by Fish1** [comment]
Ahh, sorry. I'm pretty sure that I was testing it when it was in the past and it didn't work. Either way, Ill close this because since this I've moved on to writing my own golang wrapper.
