### ISSUE TITLE
Change reference of "d" in polygon minute bar to "t"

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/alpaca-trade-api-go#8]
Please refer to https://github.com/alpacahq/alpaca-trade-api-python/pull/49

https://github.com/alpacahq/alpaca-trade-api-go/blob/24df4fb1bc10d04cecef5401516bdd619ca63081/polygon/entities.go#L105

**Comment by ttt733** [comment]
Addressed by PR #15
