### ISSUE TITLE
Spelling error in AccountActivity type

### ISSUE THREAD

**Issue by cartman-dev** [alpacahq/alpaca-trade-api-go#84]
AccountActivity type is spelled "AccountActvity" in several places.

1. alpaca/entities.go @222
`type AccountActvity struct {`
1. alpaca/rest.go @150
`func (c *Client) GetAccountActivities(activityType *string, opts *AccountActivitiesRequest) ([]AccountActvity, error) {`
1. alpaca/rest.go @191
`activities := []AccountActvity{}`
1. alpaca/rest.go @716
`func GetAccountActivities(activityType *string, opts *AccountActivitiesRequest) ([]AccountActvity, error) {`

**Comment by shlomikushchi** [comment]
thanks
