### ISSUE TITLE
Account Updates not working on wss://paper-api.alpaca.markets/stream

### ISSUE THREAD

**Issue by Connah-rs** [alpacahq/alpaca-trade-api-go#89]
Hello, 

Subscriptions to account updates on wss://paper-api.alpaca.markets/stream are confirmed with `{listening map[streams:[account_updates]]}` however we do not receive any account updates after seeing this message.

I initially encountered this issue while writing a custom API however I have chosen to reproduce it using this repo.

Steps for reproduction:

`git clone https://github.com/Connah-rs/alpaca-trade-api-go.git`
`cd alpaca-trade-api-go/examples/long-short`
replace YOUR_API_KEY_HERE, YOUR_API_SECRET_HERE in long-short.go with your paper keys 
`go run long-short.go` (to create some account activity)

in another terminal:
`cd alpaca-trade-api-go/issue`
replace YOUR_API_KEY_HERE, YOUR_API_SECRET_HERE in main.go with your paper keys 
`go run main.go`

You can uncomment the lines:
```
	// if err := stream.Register(alpaca.TradeUpdates, tradeHandler); err != nil {
	// 	panic(err)
	// }
```
To check trade updates are working 

It looks to me like somebody forgot to finish implementing functionality for streaming account updates so I have added a type to alpaca/entities.go and added the appropriate switch statements in alpaca/stream.go. Just in case any of that was wrong, msg is logged after ReadJSON (shows sub confirmation and nothing after)

I also changed the wss in alpaca/stream.go so that it is always wss://paper-api.alpaca.markets/stream. We have had confirmation from alpaca that this is the correct wss for streaming account activity on paper accounts 

Any help on this would be greatly appreciated!

**Comment by gnvk** [comment]
Unfortunately account updates are no longer supported.
